"""CR-010 STOP 2 report: score N0 and the arms, paired bootstrap, the pre-registered selection rule, funnel, one-token
slice and cost. Generated by script from the saved arm files; nothing is written by hand."""

from __future__ import annotations

import json
import math
from pathlib import Path

from cumap.concepts_v4 import runner as R
from cumap.concepts_v4.pruner import norm
from cumap.cr010 import nodes_exp as E
from cumap.expert_kg.face_scorer import GoldConcept

ROOT = Path(".")


def _pct(x: float) -> str:
    return "–" if math.isnan(x) else f"{x:.3f}"


def _recalls(sc: dict) -> str:
    r = sc["recall_by_ngram_lenient"]
    return " / ".join(_pct(r[k]["recall"]) if k in r else "–" for k in "1234")


def pick_theta(rows: dict[str, dict], cfg: dict) -> float | None:
    """Freeze rule for the N2 trigger: the grid value with the highest exact micro F1 on dev; ties go to the smaller theta
    (fewer sections resampled). The 0.02 tie band belongs to the ARM selection, not to this choice: applied here it
    would pick a theta that never fires. Always-trigger ('all') is a reference only and never selected."""
    grid = [t for t in rows if t != "all"]
    if not grid:
        return None
    best = max(rows[t]["exact"]["f1"] for t in grid)
    return float(min((t for t in grid if rows[t]["exact"]["f1"] >= best - 1e-12), key=float))


def residual_gold(out0: R.RunOutput, preds0, gold: list[GoldConcept]) -> dict[str, set[str]]:
    """Gold names N0 does not match exactly, per section (the recall gap the arms try to close)."""
    matched: dict[str, set[str]] = {}
    gold = [g for g in gold if g.section_id in preds0]
    from cumap.expert_kg.face_scorer import PredictedConcept, match_predictions

    pc = [
        PredictedConcept(sid, m["canonical_name"], m["role"])
        for sid, ms in preds0.items()
        for m in ms
    ]
    for r in match_predictions(pc, gold, lenient=False):
        if r.matched_gold is not None:
            matched.setdefault(r.predicted.section_id, set()).add(r.matched_gold.concept)
    res: dict[str, set[str]] = {}
    for g in gold:
        if g.concept not in matched.get(g.section_id, set()):
            res.setdefault(g.section_id, set()).add(g.concept)
    return res


def write_report(split, cfg, out0, sections, emph, gold, nlp, embed, pruner_for, tau) -> str:
    d = E.OUT / split
    sc = {"N0": E.score_arm(None, out0, sections, gold, nlp, embed)}
    runs: dict[str, E.ArmRun] = {}
    for arm in ("N1", "N3"):
        if (d / f"{arm}.json").exists():
            runs[arm] = E.load_arm(d / f"{arm}.json")
            sc[arm] = E.score_arm(runs[arm], out0, sections, gold, nlp, embed)
    theta_rows: dict[str, dict] = {}
    n2_cost = 0.0
    sp = d / "N2_samples.json"
    theta = cfg["n2"]["trigger_frozen"]
    if sp.exists():
        samples = json.loads(sp.read_text())
        n2_cost = round(sum(v.get("cost_usd", 0.0) for v in samples.values()), 4)
        grid = [theta] if split == "test" else [*cfg["n2"]["trigger_grid"], None]
        for t in grid:
            run = E.replay_n2(
                out0, sections, emph, samples, t, nlp=nlp, pruner_for=pruner_for, tau=tau
            )
            theta_rows["all" if t is None else str(t)] = {
                **E.score_arm(run, out0, sections, gold, nlp, embed),
                "triggered": sum(x["triggered"] for x in run.details.values()),
                "calls": run.calls,
                "_run": run,
            }
        if split == "dev":
            theta = pick_theta(theta_rows, cfg)
        key = str(theta)
        if key in theta_rows:
            sc["N2"] = theta_rows[key]
            runs["N2"] = theta_rows[key]["_run"]
    rep_path = d / "N0rep.json"
    if split == "test" and rep_path.exists():
        out_rep = E.X.load_run(rep_path)
        sc["N0rep"] = E.score_arm(None, out_rep, sections, gold, nlp, embed)
    cmp_rows = {a: E.compare(sc["N0"], sc[a], cfg) for a in sc if a not in {"N0", "N0rep"}}
    chosen, verdict = E.select_node_arm(cmp_rows, cfg) if cmp_rows else ("N0", {})
    preds0 = R.predictions(out0, sections, E.X.gold_names(gold))
    resid = residual_gold(out0, preds0, gold)
    n_resid = sum(len(v) for v in resid.values())
    L = [
        f"# CR-010 STOP 2 — node residual recall, IIR {split} ({len(sections)} sections)"
        + (" — HELD-OUT, run once" if split == "test" else ""),
        "",
        (
            "N0 = the frozen CR-009 pipeline (G1, depth 1, M4/M5 off, pruner tau "
            f"{tau}, no strict G-links). Arms are post-passes over the N0 run; selection by the pre-registered rule "
            "(`configs/cr010_node.yaml`): exact micro F1 +0.02 or paired section-bootstrap 95% lower bound > 0, precision "
            "drop <= 0.02, tie band 0.02 (simpler wins), no change allowed."
        ),
        "",
        "## Metrics",
        "",
        "| arm | predicted | exact P / R / **F1** | Δ F1 vs N0 | bootstrap 95% [lo, hi] | precision drop | lenient F1 | macro F1 | recall 1/2/3/4-gram (lenient) | one-token recall exact / lenient | rescue precision (exact) | cost |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for a, s in sc.items():
        e = s["exact"]
        c = cmp_rows.get(a) or (E.compare(sc["N0"], s, cfg) if a == "N0rep" else None)
        rp = (
            f"{s['added_exact_tp']}/{s['added_items']}"
            if s["added_items"]
            else ("–" if a != "N0" else "")
        )
        cost = {"N1": runs.get("N1"), "N3": runs.get("N3")}.get(a)
        cost_s = (
            f"${cost.cost_usd}"
            if cost is not None
            else (f"${n2_cost}" if a == "N2" else "$0 (reused)")
        )
        L.append(
            f"| {a} | {s['n_predicted']} | {e['precision']:.3f} / {e['recall']:.3f} / **{e['f1']:.3f}** | "
            + (
                f"{c['delta']:+.3f} | [{c['lo95']:+.3f}, {c['hi95']:+.3f}] | {c['precision_drop']:+.3f}"
                if c
                else "– | – | –"
            )
            + f" | {s['lenient_micro_f1']:.3f} | {s['exact_macro_f1']:.3f} | {_recalls(s)} | "
            f"{_pct(s['one_token_recall_exact'])} / {_pct(s['one_token_recall_lenient'])} | {rp} | {cost_s} |"
        )
    if split == "dev":
        L += ["", "## Selection by the pre-registered rule", ""]
        if verdict:
            L += ["| arm | gain ok | precision ok | qualifies |", "|---|---|---|---|"]
            L += [
                f"| {a} | {v['gain_ok']} | {v['precision_ok']} | {v['qualifies']} |"
                for a, v in verdict.items()
            ]
        L += ["", f"**Rule outcome: {chosen}**" + (" (no change)" if chosen == "N0" else ""), ""]
    else:
        n1 = verdict.get("N1")
        L += [
            "",
            "## Confirmatory outcome (N1 only) and descriptive arms",
            "",
            (
                "Frozen before this run: **N1 is the sole confirmatory arm; N2 and N3 are descriptive.** The criteria "
                "are the same as on dev (exact micro F1 +0.02, or paired section-bootstrap 95% lower bound > 0, with a "
                "precision drop <= 0.02), against the **frozen CR-009 N0** (historical comparator). Nothing is "
                "adopted here; the N1/N0 decision belongs to Research."
            ),
            "",
            "| arm | role | gain ok | precision ok | meets the criteria |",
            "|---|---|---|---|---|",
        ]
        for a, v in verdict.items():
            role = "confirmatory" if a == "N1" else "descriptive"
            L.append(f"| {a} | {role} | {v['gain_ok']} | {v['precision_ok']} | {v['qualifies']} |")
        if n1 is not None:
            L += [
                "",
                f"**N1 meets the pre-registered criteria on the held-out split: {n1['qualifies']}.**",
            ]
        dev_scores = ROOT / "data/processed/cr010/dev/scores.json"
        if dev_scores.exists() and "N1" in cmp_rows:
            dv = json.loads(dev_scores.read_text())["compare"].get("N1")
            if dv:
                L += [
                    "",
                    (
                        f"Dev vs test for N1: dev Δ F1 {dv['delta']:+.3f} (95% [{dv['lo95']:+.3f}, {dv['hi95']:+.3f}]); "
                        f"test Δ F1 {cmp_rows['N1']['delta']:+.3f} "
                        f"(95% [{cmp_rows['N1']['lo95']:+.3f}, {cmp_rows['N1']['hi95']:+.3f}])."
                    ),
                ]
        if "N0rep" in sc:
            rep = E.compare(sc["N0"], sc["N0rep"], cfg)
            L += [
                "",
                "### Baseline stability (fresh N0 replication, sensitivity check only)",
                "",
                (
                    f"Frozen CR-009 N0 F1 {sc['N0']['exact']['f1']:.3f}; fresh N0 replication F1 "
                    f"{sc['N0rep']['exact']['f1']:.3f} (Δ {rep['delta']:+.3f}, paired 95% "
                    f"[{rep['lo95']:+.3f}, {rep['hi95']:+.3f}]). For reference, the arms relative to the fresh replication:"
                ),
                "",
            ]
            for a in ("N1", "N2", "N3"):
                if a in sc:
                    c2 = E.compare(sc["N0rep"], sc[a], cfg)
                    L.append(
                        f"- {a} vs N0rep: Δ F1 {c2['delta']:+.3f} (95% [{c2['lo95']:+.3f}, {c2['hi95']:+.3f}]), precision change {-c2['precision_drop']:+.3f}"
                    )
            L += [
                "",
                "(The arms are post-passes over the frozen N0 run, so they are paired with it; the comparison with the fresh replication is on the same sections but not the same generated items.)",
            ]
        L.append("")
    if theta_rows:
        L += [
            "## N2 trigger (items per 100 words in N0's final output below theta)",
            "",
            "| theta | sections resampled | exact P / R / F1 | cost of samples |",
            "|---|---|---|---|",
        ]
        for t, r in theta_rows.items():
            e = r["exact"]
            L.append(
                f"| {t} | {r['triggered']} / {len(sections)} | {e['precision']:.3f} / {e['recall']:.3f} / {e['f1']:.3f} | (samples for all sections: ${n2_cost}) |"
            )
        L += [
            "",
            f"Frozen trigger rule: highest exact micro F1 on dev, ties to the smaller theta; 'all' is a reference only. "
            f"Value on this split: **{theta}**"
            + (
                " (to be written to `n2.trigger_frozen` BEFORE the test run)."
                if split == "dev"
                else "."
            ),
            "",
        ]
    L += ["## Rescue funnel (N1 / N3)", ""]
    L += [
        "| arm | candidates | one-token candidates | add_new | link_existing | reject | proposed items | verified | deduplicated | pruned | kept | incomplete decisions | schema errors |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for a in ("N1", "N3"):
        if a not in runs:
            continue
        ds = runs[a].details.values()
        g = lambda k, ds=ds: sum(x["funnel"].get(k, 0) for x in ds)
        o = lambda k, ds=ds: sum(x["outcomes"].get(k, 0) for x in ds)
        L.append(
            f"| {a} | {sum(x['candidates'] for x in ds)} | {sum(x['one_token_candidates'] for x in ds)} | {o('add_new')} | {o('link_existing')} | {o('reject')} | {g('proposed')} | {g('verified')} | {g('deduplicated')} | {g('pruned')} | {g('kept')} | {sum(x['incomplete'] for x in ds)} | {sum(1 for x in ds if x['error'])} |"
        )
    # candidate coverage of the residual gold
    L += [
        "",
        f"## Candidate coverage of N0's residual gold ({n_resid} exact-unmatched gold terms)",
        "",
    ]
    for a in ("N1", "N3"):
        if a not in runs:
            continue
        cand = {sid: {c["term"] for c in x["cand_list"]} for sid, x in runs[a].details.items()}
        inc = sum(
            1 for sid, names in resid.items() for n in names if norm(n) in cand.get(sid, set())
        )
        kept = {
            sid: {norm(n) for n in x["funnel"]["kept_names"]} for sid, x in runs[a].details.items()
        }
        won = sum(
            1 for sid, names in resid.items() for n in names if norm(n) in kept.get(sid, set())
        )
        rej = sum(
            1
            for sid, names in resid.items()
            for dcs in [runs[a].details.get(sid, {}).get("decisions", [])]
            for n in names
            if any(
                x["decision"] == "reject"
                and any(
                    c["cid"] == x["candidate_id"] and c["term"] == norm(n)
                    for c in runs[a].details[sid]["cand_list"]
                )
                for x in dcs
            )
        )
        L.append(
            f"- {a}: residual gold in the candidate list {inc}/{n_resid}; recovered by the rescue (kept, exact name) {won}; candidate rejected by the model {rej}."
        )
    L += [
        "",
        f"Partial-span errors (false positives containing / inside a gold term), N0: {sc['N0']['partial_span_errors']}",
        "",
    ]
    for a in sc:
        if a != "N0":
            L.append(f"- {a}: {sc[a]['partial_span_errors']}")
    out_md = ROOT / "reports" / f"cr010_stop2_{split}.md"
    out_md.write_text("\n".join(L) + "\n", encoding="utf-8")
    (d / "scores.json").write_text(
        json.dumps(
            {
                "scores": {
                    a: {k: v for k, v in s.items() if k not in {"sec_counts", "_run"}}
                    for a, s in sc.items()
                },
                "compare": cmp_rows,
                "verdict": verdict,
                "chosen": chosen,
                "theta": theta,
            },
            indent=1,
            default=str,
        ),
        encoding="utf-8",
    )
    return str(out_md)
