"""CR-007 §5.1: apply a registry patch (configs/registry-patches/*.yaml) to a base registry and write
the next minor version. Nothing is changed in the base file (a registry change needs a new version and
a DECISIONS entry). Usage:

    uv run python -m cumap.schemas.registry_patch configs/relations_v1.yaml \\
        configs/registry-patches/CR-007-relations-v1.1.yaml configs/relations_v1.1.yaml
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml


def apply_patch(base: dict, patch: dict) -> dict:
    """Return a new registry dict = base + patch (never mutates its inputs)."""
    if patch.get("patch_for_registry_version") != base.get("version"):
        raise ValueError(
            f"patch is for registry version {patch.get('patch_for_registry_version')!r}, "
            f"base is {base.get('version')!r}"
        )
    out = yaml.safe_load(yaml.safe_dump(base, sort_keys=False))  # deep copy
    adds = patch.get("adds", {})
    new_minor = int(str(patch["new_version"]).split(".")[1])
    out["minor"] = new_minor
    out["node_types"] = list(dict.fromkeys([*out["node_types"], *adds.get("node_types", [])]))

    for name, q in adds.get("qualifiers", {}).items():
        if name in out["qualifiers"]:
            raise ValueError(f"qualifier {name!r} already exists in the base registry")
        out["qualifiers"][name] = q
    updates = {
        **patch.get("qualifier_applies_to_updates", {}),
        **adds.get("qualifier_applies_to_updates", {}),
    }
    for name, upd in updates.items():
        out["qualifiers"][name].update(upd)

    if adds.get("output_fields"):
        out["output_fields"] = adds["output_fields"]
    for fam, gloss in patch.get("family_gloss", {}).items():
        for f in out["families"]:
            if f["name"] == fam:
                f["gloss"] = gloss

    existing = {r["name"] for r in out["relations"]}
    for rel in adds.get("relations", []):
        if rel["name"] in existing:
            raise ValueError(f"relation {rel['name']!r} already exists in the base registry")
        last = max(
            (i for i, r in enumerate(out["relations"]) if r.get("family") == rel["family"]),
            default=len(out["relations"]) - 1,
        )
        out["relations"].insert(last + 1, rel)
        existing.add(rel["name"])
    return out


def header(base_path: Path, patch_path: Path, new_version: str) -> str:
    return (
        f"# Relation registry v{new_version}: GENERATED by cumap.schemas.registry_patch from "
        f"{base_path.name} + {patch_path.name} (CR-007).\n"
        f"# Do not hand-edit: change the patch file and regenerate. {base_path.name} is unchanged.\n"
        "# Base design notes (families, qualifier rules, template/near-miss guideline design) live in "
        f"{base_path.name}.\n\n"
    )


def main(argv: list[str]) -> None:
    base_path, patch_path, out_path = (Path(a) for a in argv)
    base = yaml.safe_load(base_path.read_text())
    patch = yaml.safe_load(patch_path.read_text())
    new = apply_patch(base, patch)
    text = yaml.safe_dump(new, sort_keys=False, width=110, allow_unicode=True)
    out_path.write_text(
        header(base_path, patch_path, str(patch["new_version"])) + text, encoding="utf-8"
    )
    print(f"wrote {out_path} ({len(new['relations'])} relations)")


if __name__ == "__main__":
    main(sys.argv[1:])
