"""Generates reports/m1_eda_saf.md from the SAF splits (BUILD_PLAN M1 task 5).

Reads `answer_feedback` (privileged, rule 10) only to print a handful of example
pairs for human review — this script is not part of the diagnosis/baseline
pipeline, which must never read that column.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from cumap.data.saf import SPLIT_NAMES, load_all_splits, load_split


def _length_stats(series: pd.Series) -> dict:
    chars = series.str.len()
    words = series.str.split().str.len()
    return {
        "n": len(series),
        "chars_mean": round(chars.mean(), 1),
        "chars_median": round(chars.median(), 1),
        "words_mean": round(words.mean(), 1),
        "words_median": round(words.median(), 1),
    }


def _markdown_table(rows: list[dict]) -> str:
    if not rows:
        return "_none_\n"
    cols = list(rows[0].keys())
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join(["---"] * len(cols)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(str(row[c]) for c in cols) + " |")
    return "\n".join(lines) + "\n"


def generate_eda_report(raw_dir: Path, out_path: Path) -> Path:
    all_df = load_all_splits(raw_dir)

    lines: list[str] = []
    lines.append("# M1 EDA — SAF Communication Networks (English)\n")
    lines.append(
        "Generated by `cumap data eda` (src/cumap/data/eda.py). "
        "`answer_feedback` examples below are shown for human review only; "
        "no other pipeline code reads that column (CLAUDE.md rule 10).\n"
    )

    lines.append("## 1. Split sizes and question overlap\n")
    split_rows = []
    for split in SPLIT_NAMES:
        df = load_split(raw_dir, split)
        split_rows.append({"split": split, "rows": len(df), "distinct_questions": df["question"].nunique()})
    lines.append(_markdown_table(split_rows))

    seen_qs = set(load_split(raw_dir, "train")["question"])
    uq_qs = set(load_split(raw_dir, "test_unseen_questions")["question"])
    lines.append(
        f"\nAll 26 questions in `train`/`validation`/`test_unseen_answers` are the same set "
        f"(seen questions, new answers). `test_unseen_questions` has {len(uq_qs)} questions, "
        f"all disjoint from the seen set (`{len(uq_qs & seen_qs)}` overlap) — genuinely new topics, "
        "not just reworded seen questions. Total distinct question texts across the whole "
        f"dataset: {all_df['question'].nunique()}.\n"
    )
    lines.append(
        "**Near-duplicate phrasings found:** the two \"TCP congestion control\" question rows "
        "differ only in a trailing \"total.\" vs \".\" — same reference answer, same topic, counted "
        "as two distinct question texts (and so two distinct `question_id`s). This is likely why "
        "the dataset card's count (26) differs from the paper's (22): a few of the 26 are cosmetic "
        "rewordings of the same underlying question, not new topics. Treat this when picking pilot "
        "questions — check for a sibling phrasing before assuming a topic is only asked once.\n"
    )

    lines.append("## 2. Score scale (important finding)\n")
    lines.append(
        "`score` is **not** a global 0-1 fraction as BUILD_PLAN assumed — it is an absolute point "
        "value whose maximum varies **per question** (seen from `verification_feedback == 'Correct'` "
        "always landing at that question's max, and per-question max ranging from 1.0 up to 3.5). "
        "M4's use of \"SAF score as a hint\" for proposition weights must first normalise by "
        "`score / per_question_max_score`, not use `score` directly.\n"
    )
    per_q_max = all_df.groupby("question")["score"].max()
    lines.append(_markdown_table([{"per_question_max_score": v, "n_questions": c}
                                   for v, c in per_q_max.value_counts().sort_index().items()]))

    lines.append("\n## 3. Label distribution\n")
    lines.append(_markdown_table(
        [{"split": s, **load_split(raw_dir, s)["verification_feedback"].value_counts().to_dict()}
         for s in SPLIT_NAMES]
    ))

    lines.append("\n## 4. Text length stats (all splits combined)\n")
    length_rows = []
    for col in ["question", "reference_answer", "provided_answer", "answer_feedback"]:
        stats = _length_stats(all_df[col].fillna(""))
        length_rows.append({"field": col, **stats})
    lines.append(_markdown_table(length_rows))

    lines.append("\n## 5. Example (answer, feedback) pairs per label\n")
    train = load_split(raw_dir, "train")
    for label in ["Correct", "Partially correct", "Incorrect"]:
        lines.append(f"\n### {label}\n")
        examples = train[train["verification_feedback"] == label].sample(
            n=min(3, (train["verification_feedback"] == label).sum()), random_state=42
        )
        for _, row in examples.iterrows():
            lines.append(f"**Q:** {row['question'][:150]}\n")
            lines.append(f"**Answer:** {row['provided_answer'][:400]}\n")
            lines.append(f"**Feedback:** {row['answer_feedback'][:300]}\n")
            lines.append(f"**Score:** {row['score']}\n\n---\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    return out_path
